version: "3.7"
services:
  carbon-budget:
    build:
      context: .
    volumes:
      - ./:/usr/local/app
      - $HOME/.aws:/root/.aws:ro
      - C:/GIS/Carbon_model/test_tiles/docker_output/:/tmp
    working_dir: /usr/local/app
    entrypoint: /bin/bash